[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
seeds = false
resolution = true
skip-lint = false

[programs.localnet]
gazibo = "5bTvxVfSwqy7FApuPfHiXBWihZSmLSQNsGwVebNeLj7D"

[registry]
url = "https://api.apr.dev/"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
