[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
seeds = false
resolution = true
skip-lint = false

[programs.localnet]
gazibo = "E5fzH1DgUovmKF5GFxg5FrMj1ka89K9r9p83TL6N4xFC"

[registry]
url = "https://api.apr.dev/"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
